<?php

use App\View;

/** @var mixed $content */
/** @var array $data */
?>
<!DOCTYPE html>
<html class="page" lang="ru">
<head>
    <!-- Meta -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title><?= TITLE.' ⦿ '.$data['page_title']; ?></title>
    <meta name="description" content="<?= $data['page_subtitle']; ?>">

    <!-- Favicon generated by https://realfavicongenerator.net/ -->
    <link rel="apple-touch-icon" sizes="180x180" href="/assets/images/favicon/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/assets/images/favicon/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/assets/images/favicon/favicon-16x16.png">
    <link rel="manifest" href="/assets/images/favicon/site.webmanifest">
    <link rel="mask-icon" href="/assets/images/favicon/safari-pinned-tab.svg" color="<?= MASK_COLOR; ?>">
    <link rel="shortcut icon" href="/assets/images/favicon/favicon.ico">
    <meta name="msapplication-TileColor" content="<?= MASK_COLOR; ?>">
    <meta name="theme-color" content="<?= THEME_COLOR; ?>">

    <script src="/libs/tailwindcss.js"></script>
</head>

<body class="page__body bg-gray-100">
<div class="relative bg-white mb-10 sm:mb-24">
    <div class="max-w-7xl mx-auto px-6">
        <div class="sm:flex flex-wrap justify-between items-center border-b-2 border-gray-100 py-6 justify-start sm:space-x-10">
            <div class="flex flex-1 justify-center sm:justify-start mb-4 sm:mb-0">
                <a href="/" class="block w-10 h-10">
                    <span class="sr-only">Workflow</span>
                    <img class="block w-full" src="https://tailwindui.com/img/logos/workflow-mark-indigo-600.svg"
                         alt="">
                </a>
            </div>
            <nav class="flex flex-wrap gap-4 justify-center sm:justify-start mb-4 sm:mb-0">
                <a href="/files/create"
                   class="text-base whitespace-nowrap font-medium text-gray-500 hover:text-gray-900">Отправить файл</a>
                <a href="/files" class="text-base whitespace-nowrap font-medium text-gray-500 hover:text-gray-900">Список
                    файлов</a>
            </nav>
            <div class="flex items-center justify-center sm:justify-end flex-1">

            </div>
        </div>
    </div>
</div>

<div class="container mx-auto px-4 pb-24">
    <?= $content ?>
</div>

<?php
View::printJs();
?>
</body>
</html>
